modLoader="javafml"
loaderVersion="[35,)"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/LiskoSlayer63/TinyChest/issues"

[[mods]]
modId="tinychest"
version="1.4.1"

displayName="TinyChest"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tinychest"
logoFile="tinychest.png"
authors="LiskoSlayer63"

description='''
Adds tiny chests!
'''

[[dependencies.tinychest]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.tinychest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.tinychest]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4,)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.tinychest]]
    modId="atmospheric"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"